# -*- coding: utf-8 -*-
"""Hw5_RSA_Munjal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FfLzWodJ_71ne5tPCZjCChykWYWGsWS-
"""

!pip install pycryptodome
from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_v1_5
import binascii

UID = 117530445
Last_name = "Thakkar"
First_name = "Munjal"

def rsa_enc_public(inputblock, keypair):
  
    pubKey = keypair.publickey()
    pubKeyPEM = pubKey.exportKey()
    privKeyPEM = keypair.exportKey()
    encryptor = PKCS1_v1_5.new(pubKey)
    ciphertext = encryptor.encrypt(inputblock)
    return ciphertext

def rsa_dec_private(cipherblock, keypair):
    pubKey = keypair.publickey()
    pubKeyPEM = pubKey.exportKey()
    privKeyPEM = keypair.exportKey()
    decryptor = PKCS1_v1_5.new(keypair)
    plaintext = decryptor.decrypt(cipherblock, None)
    return plaintext

if __name__=="__main__":
    keypair = RSA.generate(2048)
    #Encryption using RSA
    inputblock = b'A message for encryption'
    cipherblock = rsa_enc_public(inputblock, keypair)
    print (cipherblock)
    #print("Encrypted:", binascii.hexlify(encrypted))
    
    #Decryption of RSA
    plaintext = rsa_dec_private(cipherblock, keypair)
    print(plaintext)